version: "3.3"

services:
  mitsuba:
    image: mitsuba/mitsuba:latest
    container_name: "mitsuba"
    restart: always
    command: "./mitsuba start"
    volumes:
      - ./data:/data
    ports:
      - "8085:8080"
      - "9025:9000"
    environment:
      - "DATA_ROOT=/home/mitsuba/data"
      - "RUST_LOG=mitsuba=info"
      - "DATABASE_URL=postgres://mitsuba:postgres1@db/mitsuba"
  db:
    image: postgres:13.2
    container_name: "mitsuba-postgres"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres1
      POSTGRES_USER: mitsuba